name: Ansible Test

on: [push]

jobs:
  sanity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/scsitteam/atlassian
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/scsitteam/atlassian

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          
      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible 
      - name: Run sanity tests
        run: ansible-test sanity -v --color